In [4]:
# Import all required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# Set visualization style (makes graphs look better)
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (10, 6)
print("Libraries imported successfully!")

Libraries imported successfully!

In [6]:
# Load the CSV file from your data folder
df = pd.read_csv('C:/Users/achar/OneDrive/Documents/GitHub/data-analytics-projects/Travel-Hospitality-Project/Data/hotel_bookings.csv')

print("Data loaded successfully!")
print("Dataset shape:", df.shape)

Data loaded successfully!
Dataset shape: (117430, 39)

In [7]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,total_of_special_requests,reservation_status,reservation_status_date,total_stay,lead_time_bucket,total_guests,has_weekend,arrival_month,is_summer,adr_per_person
0,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,0,Check-Out,2015-07-02,1,Last Minute (0-7),1,0,7,1,75.0
1,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,0,Check-Out,2015-07-02,1,Short (8-30),1,0,7,1,75.0
2,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,1,Check-Out,2015-07-03,2,Short (8-30),2,0,7,1,49.0
3,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,1,Check-Out,2015-07-03,2,Short (8-30),2,0,7,1,49.0
4,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,0,Check-Out,2015-07-03,2,Last Minute (0-7),2,0,7,1,53.5

In [8]:
print(df.columns.tolist())

['hotel', 'is_canceled', 'lead_time', 'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'meal', 'country', 'market_segment', 'distribution_channel', 'is_repeated_guest', 'previous_cancellations', 'previous_bookings_not_canceled', 'reserved_room_type', 'assigned_room_type', 'booking_changes', 'deposit_type', 'agent', 'company', 'days_in_waiting_list', 'customer_type', 'adr', 'required_car_parking_spaces', 'total_of_special_requests', 'reservation_status', 'reservation_status_date', 'total_stay', 'lead_time_bucket', 'total_guests', 'has_weekend', 'arrival_month', 'is_summer', 'adr_per_person']

In [9]:
print(df.dtypes)

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                            int64
babies                              int64
meal                               object
country                            object
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                               int64
company                             int64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
total_stay                          int64
lead_time_bucket                   object
total_guests                        int64
has_weekend                         int64
arrival_month                       int64
is_summer                           int64
adr_per_person                    float64
dtype: object

In [10]:
print(df.isnull().sum())

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
total_stay                        0
lead_time_bucket                  0
total_guests                      0
has_weekend                       0
arrival_month                     0
is_summer                         0
adr_per_person                    0
dtype: int64

In [11]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,...,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,total_stay,total_guests,has_weekend,arrival_month,is_summer,adr_per_person
count,117430.000000,117430.000000,117430.000000,117430.000000,117430.000000,117430.000000,117430.000000,117430.000000,117430.000000,117430.000000,...,117430.000000,117430.000000,117430.000000,117430.000000,117430.000000,117430.000000,117430.000000,117430.000000,117430.000000,117430.000000
mean,0.374785,105.084340,2016.160274,27.136779,15.802819,0.936422,2.521221,1.860632,0.104505,0.007869,...,2.337937,103.154720,0.062642,0.571038,3.457643,1.973005,0.569965,6.546061,0.315260,55.690555
std,0.484069,106.907012,0.706565,13.575680,8.783582,0.995760,1.893742,0.482102,0.399690,0.097168,...,17.677053,45.410494,0.245565,0.791655,2.534835,0.647247,0.495083,3.083506,0.464621,27.188334
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.260000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,0.000000,19.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,...,0.000000,70.530000,0.000000,0.000000,2.000000,2.000000,0.000000,4.000000,0.000000,37.500000
50%,0.000000,71.000000,2016.000000,27.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,...,0.000000,95.000000,0.000000,0.000000,3.000000,2.000000,1.000000,7.000000,0.000000,49.725000
75%,1.000000,162.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,...,0.000000,126.000000,0.000000,1.000000,4.000000,2.000000,1.000000,9.000000,1.000000,66.000000
max,1.000000,709.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,4.000000,10.000000,10.000000,...,391.000000,252.000000,8.000000,5.000000,69.000000,12.000000,1.000000,12.000000,1.000000,252.000000

In [12]:
# Handle missing values

# For 'children': fill with 0 (assuming no children means 0)
df['children'] = df['children'].fillna(0).astype(int)

# For 'country': fill with 'Unknown'
df['country'] = df['country'].fillna('Unknown')

# For 'agent': fill with 0 (0 means no agent / direct booking)
df['agent'] = df['agent'].fillna(0).astype(int)

# For 'company': fill with 0 (0 means no company booking)
df['company'] = df['company'].fillna(0).astype(int)

print("✅ Missing values handled!")

# Verify no missing values remain
print("\nRemaining missing values:", df.isnull().sum().sum())

✅ Missing values handled!

Remaining missing values: 0

In [13]:
# Check ADR statistics before outlier treatment
print("ADR Statistics BEFORE treatment:")
print(df['adr'].describe())

# Cap outliers at 99th percentile
upper_limit = df['adr'].quantile(0.99)
print(f"\nCapping ADR at 99th percentile: {upper_limit:.2f}")

df['adr'] = df['adr'].apply(lambda x: upper_limit if x > upper_limit else x)

# Remove negative ADR (if any)
df = df[df['adr'] > 0]

print(f"\n Outliers treated!")
print(f"Final dataset shape: {df.shape}")

ADR Statistics BEFORE treatment:
count    117430.000000
mean        103.154720
std          45.410494
min           0.260000
25%          70.530000
50%          95.000000
75%         126.000000
max         252.000000
Name: adr, dtype: float64

Capping ADR at 99th percentile: 252.00

 Outliers treated!
Final dataset shape: (117430, 39)

In [14]:
# Total stay duration (weekend nights + week nights)
df['total_stay'] = df['stays_in_weekend_nights'] + df['stays_in_week_nights']

print(" Created 'total_stay' feature")
print(df['total_stay'].describe())

 Created 'total_stay' feature
count    117430.000000
mean          3.457643
std           2.534835
min           1.000000
25%           2.000000
50%           3.000000
75%           4.000000
max          69.000000
Name: total_stay, dtype: float64

In [15]:
# Lead time buckets (categorical grouping)
def lead_time_bucket(days):
    if days <= 7:
        return 'Last Minute (0-7)'
    elif days <= 30:
        return 'Short (8-30)'
    elif days <= 90:
        return 'Medium (31-90)'
    elif days <= 180:
        return 'Long (91-180)'
    else:
        return 'Very Long (180+)'

df['lead_time_bucket'] = df['lead_time'].apply(lead_time_bucket)

print(" Created 'lead_time_bucket' feature")
print("\nLead time distribution:")
print(df['lead_time_bucket'].value_counts())

 Created 'lead_time_bucket' feature

Lead time distribution:
lead_time_bucket
Medium (31-90)       29307
Long (91-180)        26311
Very Long (180+)     24553
Short (8-30)         18651
Last Minute (0-7)    18608
Name: count, dtype: int64

In [16]:
# Total guests (adults + children + babies)
df['total_guests'] = df['adults'] + df['children'] + df['babies']

print(" Created 'total_guests' feature")
print("\nTotal guests statistics:")
print(df['total_guests'].describe())

 Created 'total_guests' feature

Total guests statistics:
count    117430.000000
mean          1.973005
std           0.647247
min           0.000000
25%           2.000000
50%           2.000000
75%           2.000000
max          12.000000
Name: total_guests, dtype: float64

In [17]:

# Has weekend stay (at least 1 weekend night)
df['has_weekend'] = (df['stays_in_weekend_nights'] > 0).astype(int)

print(" Created 'has_weekend' feature")
print("\nWeekend stay distribution:")
print(df['has_weekend'].value_counts())
print(f"\nPercentage with weekend stay: {df['has_weekend'].mean() * 100:.1f}%")

 Created 'has_weekend' feature

Weekend stay distribution:
has_weekend
1    66931
0    50499
Name: count, dtype: int64

Percentage with weekend stay: 57.0%

In [18]:

# Convert month names to numbers
month_map = {
    'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5,
    'June': 6, 'July': 7, 'August': 8, 'September': 9, 'October': 10,
    'November': 11, 'December': 12
}
df['arrival_month'] = df['arrival_date_month'].map(month_map)

# Is summer (June, July, August)
df['is_summer'] = df['arrival_month'].between(6, 8).astype(int)

print(" Created 'is_summer' feature")
print(f"\nSummer bookings: {df['is_summer'].sum():,} out of {len(df):,}")
print(f"Percentage summer bookings: {(df['is_summer'].mean() * 100):.1f}%")

 Created 'is_summer' feature

Summer bookings: 37,021 out of 117,430
Percentage summer bookings: 31.5%

In [19]:
# Average Daily Rate per person
df['adr_per_person'] = df['adr'] / df['total_guests']
df['adr_per_person'] = df['adr_per_person'].replace([float('inf'), -float('inf')], 0).fillna(0)

print("Created 'adr_per_person' feature")
print("\nADR per person statistics:")
print(df['adr_per_person'].describe())

Created 'adr_per_person' feature

ADR per person statistics:
count    117430.000000
mean         55.690555
std          27.188334
min           0.000000
25%          37.500000
50%          49.725000
75%          66.000000
max         252.000000
Name: adr_per_person, dtype: float64

In [20]:

# Show all newly created features
new_features = ['total_stay', 'lead_time_bucket', 'total_guests', 'has_weekend', 'is_summer', 'adr_per_person', 'arrival_month']
print(" New features created:", new_features)

# Preview the data with new features
print("\n📊 Preview of original and new features:")
display(df[['lead_time', 'lead_time_bucket', 'total_stay', 'total_guests', 'adr', 'adr_per_person', 'is_canceled']].head(10))

 New features created: ['total_stay', 'lead_time_bucket', 'total_guests', 'has_weekend', 'is_summer', 'adr_per_person', 'arrival_month']

📊 Preview of original and new features:

,lead_time,lead_time_bucket,total_stay,total_guests,adr,adr_per_person,is_canceled
0,7,Last Minute (0-7),1,1,75.0,75.00,0
1,13,Short (8-30),1,1,75.0,75.00,0
2,14,Short (8-30),2,2,98.0,49.00,0
3,14,Short (8-30),2,2,98.0,49.00,0
4,0,Last Minute (0-7),2,2,107.0,53.50,0
5,9,Short (8-30),2,2,103.0,51.50,0
6,85,Medium (31-90),3,2,82.0,41.00,1
7,75,Medium (31-90),3,2,105.5,52.75,1
8,23,Short (8-30),4,2,123.0,61.50,1
9,35,Medium (31-90),4,2,145.0,72.50,0

In [21]:
# Final dataset shape and columns
print("=" * 50)
print("FINAL DATASET SUMMARY")
print("=" * 50)
print(f"📊 Rows: {df.shape[0]:,}")
print(f"📊 Columns: {df.shape[1]}")
print(f"\n📋 All columns ({len(df.columns)} total):")
print(df.columns.tolist())
print("\n📈 Data types:")
print(df.dtypes.value_counts())

==================================================
FINAL DATASET SUMMARY
==================================================
📊 Rows: 117,430
📊 Columns: 39

📋 All columns (39 total):
['hotel', 'is_canceled', 'lead_time', 'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'meal', 'country', 'market_segment', 'distribution_channel', 'is_repeated_guest', 'previous_cancellations', 'previous_bookings_not_canceled', 'reserved_room_type', 'assigned_room_type', 'booking_changes', 'deposit_type', 'agent', 'company', 'days_in_waiting_list', 'customer_type', 'adr', 'required_car_parking_spaces', 'total_of_special_requests', 'reservation_status', 'reservation_status_date', 'total_stay', 'lead_time_bucket', 'total_guests', 'has_weekend', 'arrival_month', 'is_summer', 'adr_per_person']

📈 Data types:
int64      24
object     13
float64     2
Name: count, dtype: int64

In [22]:
# Save the cleaned and engineered dataset
df.to_csv('C:/Users/achar/OneDrive/Documents/GitHub/data-analytics-projects/Travel-Hospitality-Project/Data/hotel_bookings.csv', index=False)

print("Cleaned data saved successfully!")
print(f" Location: C:/Users/achar/OneDrive/Documents/GitHub/data-analytics-projects/Travel-Hospitality-Project/Data/hotel_bookings.csv")
print(f" Size: {df.shape[0]:,} rows, {df.shape[1]} columns")
print("\n WEEK 1 COMPLETED SUCCESSFULLY!")

Cleaned data saved successfully!
 Location: C:/Users/achar/OneDrive/Documents/GitHub/data-analytics-projects/Travel-Hospitality-Project/Data/hotel_bookings.csv
 Size: 117,430 rows, 39 columns

 WEEK 1 COMPLETED SUCCESSFULLY!